spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters:  true #whichx mean when web give page 1 then index stats with 1
        default-page-size: 5
  datasource:
    url: jdbc:h2:mem:oddsandends
    username: sa
    password:
    driver-class-name: org.h2.Driver
